version: "3"

services:
  NOME-DO-PROJETO_db:
    image: mariadb
    container_name: NOME-DO-PROJETO_db
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - "3306"
    environment:
      - MYSQL_DATABASE=BANCO
      - MYSQL_ROOT_PASSWORD=intest

  NOME-DO-PROJETO_web:
    image: webgriffe/php-apache-base:PHP-VERSION
    container_name: NOME-DO-PROJETO_web
    ports:
      - "80"
    links:
      - NOME-DO-PROJETO_db
    volumes:
      - ./public/:/var/www/html
    environment:
      - VIRTUAL_HOST=VIRTUAL-HOST
      - APACHE_DOC_ROOT=/var/www/html

networks:
  default:
    external:
      name: webproxy
